stages:
  - build
  - test

default:
  tags:
    - ska-default

.build-docker:
  image: docker:stable
  stage: build
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - docker build -t ${CI_REGISTRY_IMAGE}/${OS_NAME} -f os/${OS_NAME}.dockerfile .
    - docker push ${CI_REGISTRY_IMAGE}/${OS_NAME}
  services:
    - docker:stable-dind

build-spackrocky:
  variables:
    OS_NAME: rockylinux
  extends: .build-docker

build-spackubuntu:
  variables:
    OS_NAME: ubuntu
  extends: .build-docker


.test:
  image: ${CI_REGISTRY_IMAGE}/${OS_NAME}
  script:
    - . /opt/spack/share/spack/setup-env.sh
    - spack find -v -l
    - spack repo add .
    - spack env create sdp
    - spack env activate sdp
    - GCC_VERSION=$(gcc --version | head -n 1)
    - GCC_VERSION=$(echo $GCC_VERSION | sed 's=gcc (.*) \([0-9\.]*\).*=\1=')
    - sed -i s/GCC_VERSION/$GCC_VERSION/ os/spack.yaml
    - cp os/spack.yaml /opt/spack/var/spack/environments/sdp/spack.yaml
    - spack concretize
    - spack install

test-rockylinux:
  needs: ["build-spackrocky"]
  variables:
    OS_NAME: rockylinux
  extends: .test

test-ubuntu:
  needs: ["build-spackubuntu"]
  variables:
    OS_NAME: ubuntu
  extends: .test
