variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - versioning
  - prepare
  - build
  - publish
  - pages

default:
  tags:
    - ska-default

# The 'IMAGE' variables allow reusing docker images between different pipelines.
# See https://confluence.skatelescope.org/display/SE/Caching+Docker+images+using+GitLab+CI+registry
versioning:
  stage: versioning
  image: bitnami/git
  script:
    # Unshallowing ensures that 'git log' works
    - git fetch --unshallow
    - echo IMAGE_ROCKYLINUX=${CI_REGISTRY_IMAGE}/rockylinux:$(git log -n 1 --pretty=format:%H -- os/rockylinux.dockerfile) > versions.env
    - echo IMAGE_UBUNTU=${CI_REGISTRY_IMAGE}/ubuntu:$(git log -n 1 --pretty=format:%H -- os/ubuntu.dockerfile) >> versions.env
    - cat versions.env
  artifacts:
    reports:
      dotenv: versions.env


.prepare:
  stage: prepare
  needs: ["versioning"]
  image: docker:stable
  variables:
    # Makes 'docker manifest' work:
    DOCKER_CLI_EXPERIMENTAL: enabled
  before_script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
  script:
    - |
      if ! docker manifest inspect $DOCKER_IMAGE > /dev/null || [ "$BUILD_DOCKER_IMAGE" = "1" ]; then
        if [ "$BUILD_DOCKER_IMAGE" = "1" ]; then
          DOCKER_CACHE_PARAMETERS="--no-cache"
        else
          DOCKER_CACHE_PARAMETERS=""
        fi
        docker build $DOCKER_BUILD_ARG ${DOCKER_CACHE_PARAMETERS} --tag $DOCKER_IMAGE -f $DOCKER_FILE .
        docker push $DOCKER_IMAGE
      fi
  services:
    - docker:stable-dind

prepare-spackrocky:
  extends: .prepare
  variables:
    DOCKER_IMAGE: ${IMAGE_ROCKYLINUX}
    DOCKER_FILE: os/rockylinux.dockerfile

prepare-spackubuntu:
  extends: .prepare
  variables:
    DOCKER_IMAGE: ${IMAGE_UBUNTU}
    DOCKER_FILE: os/ubuntu.dockerfile


.build:
  stage: build
  script:
    - . /opt/spack/share/spack/setup-env.sh
    - spack find -v -l
    - spack repo add .
    - spack env create sdp
    - spack env activate sdp
    - GCC_VERSION=$(gcc --version | head -n 1)
    - GCC_VERSION=$(echo $GCC_VERSION | sed 's=gcc (.*) \([0-9\.]*\).*=\1=')
    - sed -i s/GCC_VERSION/$GCC_VERSION/ os/spack.yaml
    - cp os/spack.yaml /opt/spack/var/spack/environments/sdp/spack.yaml
    - spack mirror add --oci-username $CI_REGISTRY_USER --oci-password $CI_REGISTRY_PASSWORD gitlab-mirror oci://$CI_REGISTRY_IMAGE/spack-buildcache
    # Ignore absent buildcache by adding "|| true"
    - spack buildcache update-index gitlab-mirror || true
    - spack concretize
    # Install base packages, one by one, and update the buildcache. In case the
    # CI job times out, the next run will be faster as it uses the buildcache.
    - |
      for package in gmake zlib-ng cfitsio fftw git gsl hdf5+cxx "openblas threads=pthreads" python py-numpy wcslib+cfitsio; do
        spack install --use-cache --no-check-signature $package
        spack buildcache push --unsigned --update-index gitlab-mirror ${package%% *}
      done

build-rockylinux:
  needs: ["versioning", "prepare-spackrocky"]
  image: ${IMAGE_ROCKYLINUX}
  extends: .build

build-ubuntu:
  needs: ["versioning", "prepare-spackubuntu"]
  image: ${IMAGE_UBUNTU}
  extends: .build

include:
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/docs.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/finaliser.gitlab-ci.yml"
  - project: "ska-telescope/templates-repository"
    file: "gitlab-ci/includes/release.gitlab-ci.yml"
